/**
 * Actual Office Daily Worksheet Data (August 2026)
 * Assigned directly to user: kavin@8chili.com (Kavin)
 */

const SAMPLE_WORKSHEET_DATA = [
  {
    id: "task-aug-03",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-03",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "â€¢ Updated Grab Pose\nâ€¢ Implemented audio changes",
    status: "Completed",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "Simulation package tested and audio synced.",
    createdAt: "2026-08-03T09:30:00Z",
    updatedAt: "2026-08-03T18:00:00Z"
  },
  {
    id: "task-aug-04",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-04",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "â€¢ Tested 4 simulations in MDI environment",
    status: "Completed",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "All 4 simulations verified without errors.",
    createdAt: "2026-08-04T09:30:00Z",
    updatedAt: "2026-08-04T18:00:00Z"
  },
  {
    id: "task-aug-05-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-05",
    projectName: "Cleaning-of-Parisson-Area",
    work: "Storyboard explanation and process walkthrough with team",
    status: "Pending",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Parisson flow alignment.",
    createdAt: "2026-08-05T09:30:00Z",
    updatedAt: "2026-08-05T13:30:00Z"
  },
  {
    id: "task-aug-05-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-05",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "Updated the simulation package and asset references",
    status: "Pending",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Awaiting final review.",
    createdAt: "2026-08-05T14:00:00Z",
    updatedAt: "2026-08-05T18:00:00Z"
  },
  {
    id: "task-aug-06-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Step Wizard â€” worked on 10 sequential simulation steps",
    status: "In Progress",
    hoursWorked: 3.5,
    priority: "High",
    remarks: "Step wizard foundation ready.",
    createdAt: "2026-08-06T09:30:00Z",
    updatedAt: "2026-08-06T13:00:00Z"
  },
  {
    id: "task-aug-06-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Cleaning of Ethanol",
    work: "Grab Pose correction and hand interaction refinement",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Medium",
    remarks: "Adjusted controller offsets.",
    createdAt: "2026-08-06T13:30:00Z",
    updatedAt: "2026-08-06T16:00:00Z"
  },
  {
    id: "task-aug-06-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Cleaning",
    work: "MDI Parisson Area Cleaning audio sync integration",
    status: "In Progress",
    hoursWorked: 2.0,
    priority: "Medium",
    remarks: "Audio clips connected to event triggers.",
    createdAt: "2026-08-06T16:00:00Z",
    updatedAt: "2026-08-06T18:00:00Z"
  },
  {
    id: "task-aug-06-4",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Cleaning of Purified Water",
    work: "Fixed Audio triggers, Detect Visual markers and Grab Pose",
    status: "In Progress",
    hoursWorked: 2.0,
    priority: "Medium",
    remarks: "Audio cue alignment completed.",
    createdAt: "2026-08-06T16:00:00Z",
    updatedAt: "2026-08-06T18:00:00Z"
  },
  {
    id: "task-aug-07-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "Line clearance Checklist",
    work: "Line clearance initial storyboard development & process review",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Flowchart approved by QA.",
    createdAt: "2026-08-07T09:30:00Z",
    updatedAt: "2026-08-07T13:30:00Z"
  },
  {
    id: "task-aug-07-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "MDI_Line Clearance",
    work: "Model setup and interactive asset placements for clearance module",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Environment layout finalized.",
    createdAt: "2026-08-07T14:00:00Z",
    updatedAt: "2026-08-07T18:00:00Z"
  },
  {
    id: "task-aug-07-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "MDI_Manu_Ethanol",
    work: "Updating VIVE package and VR SDK dependencies",
    status: "In Progress",
    hoursWorked: 3.0,
    priority: "High",
    remarks: "VIVE SDK upgrade in progress.",
    createdAt: "2026-08-07T14:00:00Z",
    updatedAt: "2026-08-07T17:00:00Z"
  },
  {
    id: "task-aug-07-4",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "MDI_Setup and Ops",
    work: "Updating VIVE package configuration and build settings",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Medium",
    remarks: "Testing headset tracking.",
    createdAt: "2026-08-07T14:00:00Z",
    updatedAt: "2026-08-07T16:30:00Z"
  },
  {
    id: "task-aug-07-5",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "FFS - Cleaning of Parisson Area",
    work: "Step Wizard setup and flow integration",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Medium",
    remarks: "Initial step sequence mapped.",
    createdAt: "2026-08-07T14:00:00Z",
    updatedAt: "2026-08-07T16:30:00Z"
  },
  {
    id: "task-aug-08-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-08",
    projectName: "MDI-LineClearance",
    work: "Step Wizard implementation for sequential line clearance verification",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Steps 1 through 8 completed.",
    createdAt: "2026-08-08T09:30:00Z",
    updatedAt: "2026-08-08T13:30:00Z"
  },
  {
    id: "task-aug-08-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-08",
    projectName: "MDI-LineClearance",
    work: "Updated simulation package with new assets and animation clips",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Package built and deployed to test environment.",
    createdAt: "2026-08-08T14:00:00Z",
    updatedAt: "2026-08-08T18:00:00Z"
  },
  {
    id: "task-aug-08-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-08",
    projectName: "Leave / Weekend",
    work: "Weekend / Off",
    status: "Leave",
    hoursWorked: 0,
    priority: "Low",
    remarks: "Weekend",
    createdAt: "2026-08-08T00:00:00Z",
    updatedAt: "2026-08-08T00:00:00Z"
  },
  {
    id: "task-aug-09",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-09",
    projectName: "Leave / Weekend",
    work: "Weekend / Off",
    status: "Leave",
    hoursWorked: 0,
    priority: "Low",
    remarks: "Weekend",
    createdAt: "2026-08-09T00:00:00Z",
    updatedAt: "2026-08-09T00:00:00Z"
  },
  {
    id: "task-aug-10",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-10",
    projectName: "FFS_Cleaning Of Parisson Area",
    work: "â€¢ Completed the Step Wizard for all steps\nâ€¢ Fixed Detect Visual functionality for all steps",
    status: "Completed",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "All step wizards verified and working.",
    createdAt: "2026-08-10T09:30:00Z",
    updatedAt: "2026-08-10T18:00:00Z"
  },
  {
    id: "task-aug-11-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-11",
    projectName: "MDI-LineClearance",
    work: "Simulation step update â€” corrected order of operation for steps 4 & 5",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Step sequence aligned with SOP document.",
    createdAt: "2026-08-11T09:30:00Z",
    updatedAt: "2026-08-11T13:30:00Z"
  },
  {
    id: "task-aug-11-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-11",
    projectName: "MDI-LineClearance",
    work: "Model updates & asset reference corrections across scene nodes",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Cleaned redundant mesh colliders.",
    createdAt: "2026-08-11T14:00:00Z",
    updatedAt: "2026-08-11T18:00:00Z"
  },
  {
    id: "task-aug-11-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-11",
    projectName: "FFS - Cleaning of Parisson Area",
    work: "â€¢ Worked on the Step Events\nâ€¢ Configured and updated event behavior for the simulation steps",
    status: "In Progress",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "Event triggers connected to state machine.",
    createdAt: "2026-08-11T09:30:00Z",
    updatedAt: "2026-08-11T18:00:00Z"
  },
  {
    id: "task-aug-12-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-12",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Step Wizard animation trigger fixes and interactive highlight shaders",
    status: "In Progress",
    hoursWorked: 3.5,
    priority: "Medium",
    remarks: "Highlight shader tested on target meshes.",
    createdAt: "2026-08-12T09:30:00Z",
    updatedAt: "2026-08-12T13:00:00Z"
  },
  {
    id: "task-aug-12-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-12",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Audio changes & voiceover cue timing adjustments for training module",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Low",
    remarks: "All 12 voiceover cues matched to visual actions.",
    createdAt: "2026-08-12T13:30:00Z",
    updatedAt: "2026-08-12T16:00:00Z"
  },
  {
    id: "task-aug-12-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-12",
    projectName: "MDI_Manu_Ethanol",
    work: "â€¢ Correction work on simulation models\nâ€¢ Testing on the VR platform",
    status: "In Progress",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "Performance testing on target hardware.",
    createdAt: "2026-08-12T09:30:00Z",
    updatedAt: "2026-08-12T18:00:00Z"
  },
  {
    id: "task-aug-13-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-13",
    projectName: "MDI_LineClearance",
    work: "Grab Pose refinement and controller haptic feedback implementation",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Haptic feedback curve tuned for realistic tactile feel.",
    createdAt: "2026-08-13T09:30:00Z",
    updatedAt: "2026-08-13T13:30:00Z"
  },
  {
    id: "task-aug-13-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-13",
    projectName: "Leave / Off",
    work: "Official Leave",
    status: "Leave",
    hoursWorked: 0,
    priority: "Low",
    remarks: "Approved Leave",
    createdAt: "2026-08-13T00:00:00Z",
    updatedAt: "2026-08-13T00:00:00Z"
  },
  {
    id: "task-aug-14-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-14",
    projectName: "MDI_LineClearance",
    work: "Step Wizard UI integration and full end-to-end simulation testing",
    status: "Completed",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Completed line clearance run-through with 0 errors.",
    createdAt: "2026-08-14T09:30:00Z",
    updatedAt: "2026-08-14T13:30:00Z"
  },
  {
    id: "task-aug-14-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-14",
    projectName: "Leave / Off",
    work: "Official Leave",
    status: "Leave",
    hoursWorked: 0,
    priority: "Low",
    remarks: "Approved Leave",
    createdAt: "2026-08-14T00:00:00Z",
    updatedAt: "2026-08-14T00:00:00Z"
  }
];

// Export to window
window.SAMPLE_WORKSHEET_DATA = SAMPLE_WORKSHEET_DATA;