/**
 * Actual Office Daily Worksheet Data (Aug 2026)
 * Assigned directly to user: kavin@8chili.com (Kavin)
 */

const SAMPLE_WORKSHEET_DATA = [
  {
    id: "task-aug-03",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-03",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "• Updated Grab Pose\n• Implemented audio changes",
    status: "Completed",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "Simulation package tested and audio synced.",
    createdAt: "2026-08-03T09:30:00Z",
    updatedAt: "2026-08-03T18:00:00Z"
  },
  {
    id: "task-aug-04",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-04",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "• Tested 4 simulations in MDI environment",
    status: "Completed",
    hoursWorked: 8.0,
    priority: "High",
    remarks: "All 4 simulations verified without errors.",
    createdAt: "2026-08-04T09:30:00Z",
    updatedAt: "2026-08-04T18:00:00Z"
  },
  {
    id: "task-aug-05-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-05",
    projectName: "Cleaning-of-Parisson-Area",
    work: "Storyboard explanation and process walkthrough with team",
    status: "Pending",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Parisson flow alignment.",
    createdAt: "2026-08-05T09:30:00Z",
    updatedAt: "2026-08-05T13:30:00Z"
  },
  {
    id: "task-aug-05-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-05",
    projectName: "MDI_Manu_CleaningEthanol",
    work: "Updated the simulation package and asset references",
    status: "Pending",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Awaiting final review.",
    createdAt: "2026-08-05T14:00:00Z",
    updatedAt: "2026-08-05T18:00:00Z"
  },
  {
    id: "task-aug-06-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Step Wizard — worked on 10 sequential simulation steps",
    status: "In Progress",
    hoursWorked: 3.5,
    priority: "High",
    remarks: "Step wizard foundation ready.",
    createdAt: "2026-08-06T09:30:00Z",
    updatedAt: "2026-08-06T13:00:00Z"
  },
  {
    id: "task-aug-06-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Cleaning of Ethanol",
    work: "Grab Pose correction and hand interaction refinement",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Medium",
    remarks: "Adjusted controller offsets.",
    createdAt: "2026-08-06T13:30:00Z",
    updatedAt: "2026-08-06T16:00:00Z"
  },
  {
    id: "task-aug-06-3",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-06",
    projectName: "MDI_Cleaning",
    work: "MDI Parisson Area Cleaning audio sync integration",
    status: "In Progress",
    hoursWorked: 2.0,
    priority: "Medium",
    remarks: "Audio clips connected to event triggers.",
    createdAt: "2026-08-06T16:00:00Z",
    updatedAt: "2026-08-06T18:00:00Z"
  },
  {
    id: "task-aug-07-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "Line clearance Checklist",
    work: "Line clearance initial storyboard development & process review",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Flowchart approved by QA.",
    createdAt: "2026-08-07T09:30:00Z",
    updatedAt: "2026-08-07T13:30:00Z"
  },
  {
    id: "task-aug-07-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-07",
    projectName: "MDI_Line Clearance",
    work: "Model setup and interactive asset placements for clearance module",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Environment layout finalized.",
    createdAt: "2026-08-07T14:00:00Z",
    updatedAt: "2026-08-07T18:00:00Z"
  },
  {
    id: "task-aug-08-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-08",
    projectName: "MDI-LineClearance",
    work: "Step Wizard implementation for sequential line clearance verification",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Steps 1 through 8 completed.",
    createdAt: "2026-08-08T09:30:00Z",
    updatedAt: "2026-08-08T13:30:00Z"
  },
  {
    id: "task-aug-08-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-08",
    projectName: "MDI-LineClearance",
    work: "Updated simulation package with new assets and animation clips",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Package built and deployed to test environment.",
    createdAt: "2026-08-08T14:00:00Z",
    updatedAt: "2026-08-08T18:00:00Z"
  },
  {
    id: "task-aug-11-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-11",
    projectName: "MDI-LineClearance",
    work: "Simulation step update — corrected order of operation for steps 4 & 5",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Step sequence aligned with SOP document.",
    createdAt: "2026-08-11T09:30:00Z",
    updatedAt: "2026-08-11T13:30:00Z"
  },
  {
    id: "task-aug-11-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-11",
    projectName: "MDI-LineClearance",
    work: "Model updates & asset reference corrections across scene nodes",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "Medium",
    remarks: "Cleaned redundant mesh colliders.",
    createdAt: "2026-08-11T14:00:00Z",
    updatedAt: "2026-08-11T18:00:00Z"
  },
  {
    id: "task-aug-12-1",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-12",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Step Wizard animation trigger fixes and interactive highlight shaders",
    status: "In Progress",
    hoursWorked: 3.5,
    priority: "Medium",
    remarks: "Highlight shader tested on target meshes.",
    createdAt: "2026-08-12T09:30:00Z",
    updatedAt: "2026-08-12T13:00:00Z"
  },
  {
    id: "task-aug-12-2",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-12",
    projectName: "MDI_Parisson Area Cleaning",
    work: "Audio changes & voiceover cue timing adjustments for training module",
    status: "In Progress",
    hoursWorked: 2.5,
    priority: "Low",
    remarks: "All 12 voiceover cues matched to visual actions.",
    createdAt: "2026-08-12T13:30:00Z",
    updatedAt: "2026-08-12T16:00:00Z"
  },
  {
    id: "task-aug-13",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-13",
    projectName: "MDI_LineClearance",
    work: "Grab Pose refinement and controller haptic feedback implementation",
    status: "In Progress",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Haptic feedback curve tuned for realistic tactile feel.",
    createdAt: "2026-08-13T09:30:00Z",
    updatedAt: "2026-08-13T13:30:00Z"
  },
  {
    id: "task-aug-14",
    userId: "user_8chili_kavin",
    userName: "Kavin (8chili)",
    date: "2026-08-14",
    projectName: "MDI_LineClearance",
    work: "Step Wizard UI integration and full end-to-end simulation testing",
    status: "Completed",
    hoursWorked: 4.0,
    priority: "High",
    remarks: "Completed line clearance run-through with 0 errors.",
    createdAt: "2026-08-14T09:30:00Z",
    updatedAt: "2026-08-14T13:30:00Z"
  }
];

// Export to window
window.SAMPLE_WORKSHEET_DATA = SAMPLE_WORKSHEET_DATA;
